// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "divide.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic divide::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic divide::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> divide::ap_ST_fsm_state1 = "1";
const sc_lv<3> divide::ap_ST_fsm_state2 = "10";
const sc_lv<3> divide::ap_ST_fsm_state3 = "100";
const sc_lv<32> divide::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> divide::ap_const_lv32_1 = "1";
const sc_lv<1> divide::ap_const_lv1_0 = "0";
const sc_lv<32> divide::ap_const_lv32_2 = "10";
const sc_lv<4> divide::ap_const_lv4_7 = "111";
const sc_lv<8> divide::ap_const_lv8_0 = "00000000";
const sc_lv<1> divide::ap_const_lv1_1 = "1";
const sc_lv<32> divide::ap_const_lv32_3 = "11";
const sc_lv<8> divide::ap_const_lv8_1 = "1";
const sc_lv<4> divide::ap_const_lv4_F = "1111";
const bool divide::ap_const_boolean_1 = true;

divide::divide(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Q);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln3_fu_86_p2 );
    sensitive << ( icmp_ln3_reg_203 );
    sensitive << ( icmp_ln16_fu_151_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_106_p3 );
    sensitive << ( or_ln19_fu_164_p2 );

    SC_METHOD(thread_Q_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln3_fu_86_p2 );
    sensitive << ( icmp_ln3_reg_203 );
    sensitive << ( icmp_ln16_fu_151_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_106_p3 );

    SC_METHOD(thread_R);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln3_fu_86_p2 );
    sensitive << ( icmp_ln3_reg_203 );
    sensitive << ( icmp_ln16_reg_225 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_106_p3 );
    sensitive << ( sub_ln18_reg_229 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( or_ln_fu_142_p3 );

    SC_METHOD(thread_R_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln3_fu_86_p2 );
    sensitive << ( icmp_ln3_reg_203 );
    sensitive << ( icmp_ln16_reg_225 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_106_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_and_ln12_fu_123_p2);
    sensitive << ( N );
    sensitive << ( shl_ln12_fu_117_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( icmp_ln3_reg_203 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_106_p3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( icmp_ln3_reg_203 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_106_p3 );

    SC_METHOD(thread_iBitN_fu_128_p2);
    sensitive << ( sext_ln8_fu_102_p1 );
    sensitive << ( and_ln12_fu_123_p2 );

    SC_METHOD(thread_i_fu_186_p2);
    sensitive << ( i_0_reg_74 );

    SC_METHOD(thread_icmp_ln16_fu_151_p2);
    sensitive << ( D );
    sensitive << ( icmp_ln3_reg_203 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_106_p3 );
    sensitive << ( or_ln_fu_142_p3 );

    SC_METHOD(thread_icmp_ln3_fu_86_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( D );

    SC_METHOD(thread_or_ln19_fu_164_p2);
    sensitive << ( Q_load_fu_42 );
    sensitive << ( shl_ln12_fu_117_p2 );

    SC_METHOD(thread_or_ln_fu_142_p3);
    sensitive << ( trunc_ln14_1_fu_138_p1 );
    sensitive << ( trunc_ln14_fu_134_p1 );

    SC_METHOD(thread_sext_ln8_fu_102_p1);
    sensitive << ( i_0_reg_74 );

    SC_METHOD(thread_shl_ln12_fu_117_p2);
    sensitive << ( sext_ln8_fu_102_p1 );

    SC_METHOD(thread_sub_ln18_fu_159_p2);
    sensitive << ( D );
    sensitive << ( or_ln_fu_142_p3 );

    SC_METHOD(thread_tmp_fu_106_p3);
    sensitive << ( i_0_reg_74 );

    SC_METHOD(thread_trunc_ln14_1_fu_138_p1);
    sensitive << ( R_load_fu_38 );

    SC_METHOD(thread_trunc_ln14_fu_134_p1);
    sensitive << ( iBitN_fu_128_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln3_reg_203 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_106_p3 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "divide_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, N, "(port)N");
    sc_trace(mVcdFile, D, "(port)D");
    sc_trace(mVcdFile, Q, "(port)Q");
    sc_trace(mVcdFile, Q_ap_vld, "(port)Q_ap_vld");
    sc_trace(mVcdFile, R, "(port)R");
    sc_trace(mVcdFile, R_ap_vld, "(port)R_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, icmp_ln3_fu_86_p2, "icmp_ln3_fu_86_p2");
    sc_trace(mVcdFile, icmp_ln3_reg_203, "icmp_ln3_reg_203");
    sc_trace(mVcdFile, icmp_ln16_fu_151_p2, "icmp_ln16_fu_151_p2");
    sc_trace(mVcdFile, icmp_ln16_reg_225, "icmp_ln16_reg_225");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_106_p3, "tmp_fu_106_p3");
    sc_trace(mVcdFile, sub_ln18_fu_159_p2, "sub_ln18_fu_159_p2");
    sc_trace(mVcdFile, sub_ln18_reg_229, "sub_ln18_reg_229");
    sc_trace(mVcdFile, i_fu_186_p2, "i_fu_186_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_0_reg_74, "i_0_reg_74");
    sc_trace(mVcdFile, R_load_fu_38, "R_load_fu_38");
    sc_trace(mVcdFile, or_ln_fu_142_p3, "or_ln_fu_142_p3");
    sc_trace(mVcdFile, Q_load_fu_42, "Q_load_fu_42");
    sc_trace(mVcdFile, or_ln19_fu_164_p2, "or_ln19_fu_164_p2");
    sc_trace(mVcdFile, sext_ln8_fu_102_p1, "sext_ln8_fu_102_p1");
    sc_trace(mVcdFile, shl_ln12_fu_117_p2, "shl_ln12_fu_117_p2");
    sc_trace(mVcdFile, and_ln12_fu_123_p2, "and_ln12_fu_123_p2");
    sc_trace(mVcdFile, iBitN_fu_128_p2, "iBitN_fu_128_p2");
    sc_trace(mVcdFile, trunc_ln14_1_fu_138_p1, "trunc_ln14_1_fu_138_p1");
    sc_trace(mVcdFile, trunc_ln14_fu_134_p1, "trunc_ln14_fu_134_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("divide.hdltvin.dat");
    mHdltvoutHandle.open("divide.hdltvout.dat");
}

divide::~divide() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void divide::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read()) && 
         esl_seteq<1,1,1>(icmp_ln16_fu_151_p2.read(), ap_const_lv1_0))) {
        Q_load_fu_42 = or_ln19_fu_164_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(icmp_ln3_fu_86_p2.read(), ap_const_lv1_0))) {
        Q_load_fu_42 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read()) && 
         esl_seteq<1,1,1>(icmp_ln16_fu_151_p2.read(), ap_const_lv1_1))) {
        R_load_fu_38 = or_ln_fu_142_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read()) && 
                esl_seteq<1,1,1>(icmp_ln16_fu_151_p2.read(), ap_const_lv1_0))) {
        R_load_fu_38 = sub_ln18_fu_159_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(icmp_ln3_fu_86_p2.read(), ap_const_lv1_0))) {
        R_load_fu_38 = ap_const_lv8_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_0_reg_74 = i_fu_186_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(icmp_ln3_fu_86_p2.read(), ap_const_lv1_0))) {
        i_0_reg_74 = ap_const_lv4_7;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read()))) {
        icmp_ln16_reg_225 = icmp_ln16_fu_151_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        icmp_ln3_reg_203 = icmp_ln3_fu_86_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read()) && esl_seteq<1,1,1>(icmp_ln16_fu_151_p2.read(), ap_const_lv1_0))) {
        sub_ln18_reg_229 = sub_ln18_fu_159_p2.read();
    }
}

void divide::thread_Q() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read()) && 
         esl_seteq<1,1,1>(icmp_ln16_fu_151_p2.read(), ap_const_lv1_0))) {
        Q = or_ln19_fu_164_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(icmp_ln3_fu_86_p2.read(), ap_const_lv1_0))) {
        Q = ap_const_lv8_0;
    } else {
        Q = "XXXXXXXX";
    }
}

void divide::thread_Q_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read()) && 
          esl_seteq<1,1,1>(icmp_ln16_fu_151_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(icmp_ln3_fu_86_p2.read(), ap_const_lv1_0)))) {
        Q_ap_vld = ap_const_logic_1;
    } else {
        Q_ap_vld = ap_const_logic_0;
    }
}

void divide::thread_R() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln16_reg_225.read(), ap_const_lv1_0))) {
        R = sub_ln18_reg_229.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read()))) {
        R = or_ln_fu_142_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(icmp_ln3_fu_86_p2.read(), ap_const_lv1_0))) {
        R = ap_const_lv8_0;
    } else {
        R = "XXXXXXXX";
    }
}

void divide::thread_R_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_106_p3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(icmp_ln3_fu_86_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(icmp_ln16_reg_225.read(), ap_const_lv1_0)))) {
        R_ap_vld = ap_const_logic_1;
    } else {
        R_ap_vld = ap_const_logic_0;
    }
}

void divide::thread_and_ln12_fu_123_p2() {
    and_ln12_fu_123_p2 = (shl_ln12_fu_117_p2.read() & N.read());
}

void divide::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void divide::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void divide::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void divide::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         (esl_seteq<1,1,1>(tmp_fu_106_p3.read(), ap_const_lv1_1) || 
          esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void divide::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void divide::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         (esl_seteq<1,1,1>(tmp_fu_106_p3.read(), ap_const_lv1_1) || 
          esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_1)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void divide::thread_iBitN_fu_128_p2() {
    iBitN_fu_128_p2 = (!sext_ln8_fu_102_p1.read().is_01())? sc_lv<8>(): and_ln12_fu_123_p2.read() >> (unsigned short)sext_ln8_fu_102_p1.read().to_uint();
}

void divide::thread_i_fu_186_p2() {
    i_fu_186_p2 = (!i_0_reg_74.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<4>(): (sc_bigint<4>(i_0_reg_74.read()) + sc_bigint<4>(ap_const_lv4_F));
}

void divide::thread_icmp_ln16_fu_151_p2() {
    icmp_ln16_fu_151_p2 = (!or_ln_fu_142_p3.read().is_01() || !D.read().is_01())? sc_lv<1>(): (sc_biguint<8>(or_ln_fu_142_p3.read()) < sc_biguint<8>(D.read()));
}

void divide::thread_icmp_ln3_fu_86_p2() {
    icmp_ln3_fu_86_p2 = (!D.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(D.read() == ap_const_lv8_0);
}

void divide::thread_or_ln19_fu_164_p2() {
    or_ln19_fu_164_p2 = (Q_load_fu_42.read() | shl_ln12_fu_117_p2.read());
}

void divide::thread_or_ln_fu_142_p3() {
    or_ln_fu_142_p3 = esl_concat<7,1>(trunc_ln14_1_fu_138_p1.read(), trunc_ln14_fu_134_p1.read());
}

void divide::thread_sext_ln8_fu_102_p1() {
    sext_ln8_fu_102_p1 = esl_sext<8,4>(i_0_reg_74.read());
}

void divide::thread_shl_ln12_fu_117_p2() {
    shl_ln12_fu_117_p2 = (!sext_ln8_fu_102_p1.read().is_01())? sc_lv<8>(): ap_const_lv8_1 << (unsigned short)sext_ln8_fu_102_p1.read().to_uint();
}

void divide::thread_sub_ln18_fu_159_p2() {
    sub_ln18_fu_159_p2 = (!or_ln_fu_142_p3.read().is_01() || !D.read().is_01())? sc_lv<8>(): (sc_biguint<8>(or_ln_fu_142_p3.read()) - sc_biguint<8>(D.read()));
}

void divide::thread_tmp_fu_106_p3() {
    tmp_fu_106_p3 = i_0_reg_74.read().range(3, 3);
}

void divide::thread_trunc_ln14_1_fu_138_p1() {
    trunc_ln14_1_fu_138_p1 = R_load_fu_38.read().range(7-1, 0);
}

void divide::thread_trunc_ln14_fu_134_p1() {
    trunc_ln14_fu_134_p1 = iBitN_fu_128_p2.read().range(1-1, 0);
}

void divide::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && (esl_seteq<1,1,1>(tmp_fu_106_p3.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(icmp_ln3_reg_203.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

void divide::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"N\" :  \"" << N.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"D\" :  \"" << D.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Q\" :  \"" << Q.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Q_ap_vld\" :  \"" << Q_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"R\" :  \"" << R.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"R_ap_vld\" :  \"" << R_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

