-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity csd is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    inA_V : IN STD_LOGIC_VECTOR (16 downto 0);
    inB_V : IN STD_LOGIC_VECTOR (16 downto 0);
    op : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (16 downto 0) );
end;


architecture behav of csd is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "csd,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.120875,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=76,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal icmp_ln5_fu_38_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln209_fu_50_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln214_fu_44_p2 : STD_LOGIC_VECTOR (16 downto 0);


begin



    add_ln209_fu_50_p2 <= std_logic_vector(unsigned(inB_V) + unsigned(inA_V));
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_return <= 
        add_ln209_fu_50_p2 when (icmp_ln5_fu_38_p2(0) = '1') else 
        sub_ln214_fu_44_p2;
    icmp_ln5_fu_38_p2 <= "1" when (op = ap_const_lv8_1) else "0";
    sub_ln214_fu_44_p2 <= std_logic_vector(unsigned(inA_V) - unsigned(inB_V));
end behav;
