// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="csd,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.120875,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=76,HLS_VERSION=2019_2}" *)

module csd (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_V,
        B_V,
        op,
        ap_return
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [16:0] A_V;
input  [16:0] B_V;
input  [7:0] op;
output  [16:0] ap_return;

wire   [0:0] icmp_ln5_fu_38_p2;
wire   [16:0] add_ln209_fu_50_p2;
wire   [16:0] sub_ln214_fu_44_p2;

assign add_ln209_fu_50_p2 = (B_V + A_V);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign ap_return = ((icmp_ln5_fu_38_p2[0:0] === 1'b1) ? add_ln209_fu_50_p2 : sub_ln214_fu_44_p2);

assign icmp_ln5_fu_38_p2 = ((op == 8'd1) ? 1'b1 : 1'b0);

assign sub_ln214_fu_44_p2 = (A_V - B_V);

endmodule //csd
