// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "FFT0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic FFT0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic FFT0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> FFT0::ap_ST_fsm_state1 = "1";
const sc_lv<5> FFT0::ap_ST_fsm_state2 = "10";
const sc_lv<5> FFT0::ap_ST_fsm_state3 = "100";
const sc_lv<5> FFT0::ap_ST_fsm_state4 = "1000";
const sc_lv<5> FFT0::ap_ST_fsm_state5 = "10000";
const sc_lv<32> FFT0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> FFT0::ap_const_lv32_1 = "1";
const sc_lv<1> FFT0::ap_const_lv1_0 = "0";
const sc_lv<32> FFT0::ap_const_lv32_2 = "10";
const sc_lv<32> FFT0::ap_const_lv32_3 = "11";
const sc_lv<32> FFT0::ap_const_lv32_4 = "100";
const sc_lv<5> FFT0::ap_const_lv5_0 = "00000";
const sc_lv<5> FFT0::ap_const_lv5_1F = "11111";
const sc_lv<5> FFT0::ap_const_lv5_10 = "10000";
const sc_lv<5> FFT0::ap_const_lv5_1 = "1";
const sc_lv<32> FFT0::ap_const_lv32_8 = "1000";
const sc_lv<32> FFT0::ap_const_lv32_17 = "10111";
const sc_lv<1> FFT0::ap_const_lv1_1 = "1";
const bool FFT0::ap_const_boolean_1 = true;

FFT0::FFT0(sc_module_name name) : sc_module(name), mVcdFile(0) {
    W_M_real_V_U = new FFT0_W_M_real_V("W_M_real_V_U");
    W_M_real_V_U->clk(ap_clk);
    W_M_real_V_U->reset(ap_rst);
    W_M_real_V_U->address0(W_M_real_V_address0);
    W_M_real_V_U->ce0(W_M_real_V_ce0);
    W_M_real_V_U->q0(W_M_real_V_q0);
    W_M_imag_V_U = new FFT0_W_M_imag_V("W_M_imag_V_U");
    W_M_imag_V_U->clk(ap_clk);
    W_M_imag_V_U->reset(ap_rst);
    W_M_imag_V_U->address0(W_M_imag_V_address0);
    W_M_imag_V_U->ce0(W_M_imag_V_ce0);
    W_M_imag_V_U->q0(W_M_imag_V_q0);
    FFT_mul_mul_10s_1bkb_U1 = new FFT_mul_mul_10s_1bkb<1,1,10,16,24>("FFT_mul_mul_10s_1bkb_U1");
    FFT_mul_mul_10s_1bkb_U1->din0(W_M_real_V_q0);
    FFT_mul_mul_10s_1bkb_U1->din1(mul_ln700_fu_414_p1);
    FFT_mul_mul_10s_1bkb_U1->dout(mul_ln700_fu_414_p2);
    FFT_mul_mul_16s_9cud_U2 = new FFT_mul_mul_16s_9cud<1,1,16,9,24>("FFT_mul_mul_16s_9cud_U2");
    FFT_mul_mul_16s_9cud_U2->din0(mul_ln1192_fu_420_p0);
    FFT_mul_mul_16s_9cud_U2->din1(W_M_imag_V_q0);
    FFT_mul_mul_16s_9cud_U2->dout(mul_ln1192_fu_420_p2);
    FFT_mac_mulsub_9sdEe_U3 = new FFT_mac_mulsub_9sdEe<1,1,9,16,24,24>("FFT_mac_mulsub_9sdEe_U3");
    FFT_mac_mulsub_9sdEe_U3->din0(grp_fu_426_p0);
    FFT_mac_mulsub_9sdEe_U3->din1(grp_fu_426_p1);
    FFT_mac_mulsub_9sdEe_U3->din2(mul_ln700_reg_529);
    FFT_mac_mulsub_9sdEe_U3->dout(grp_fu_426_p3);
    FFT_mac_muladd_10eOg_U4 = new FFT_mac_muladd_10eOg<1,1,10,16,24,24>("FFT_mac_muladd_10eOg_U4");
    FFT_mac_muladd_10eOg_U4->din0(grp_fu_433_p0);
    FFT_mac_muladd_10eOg_U4->din1(grp_fu_433_p1);
    FFT_mac_muladd_10eOg_U4->din2(mul_ln1192_reg_534);
    FFT_mac_muladd_10eOg_U4->dout(grp_fu_433_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_FFT_stage_cast1_fu_227_p1);
    sensitive << ( FFT_stage );

    SC_METHOD(thread_Llimit_fu_287_p2);
    sensitive << ( FFT_stage_cast1_reg_450 );
    sensitive << ( Ulimit_fu_281_p2 );

    SC_METHOD(thread_Ulimit_fu_281_p2);
    sensitive << ( butterfly_span_0_reg_186 );
    sensitive << ( shl_ln28_fu_276_p2 );

    SC_METHOD(thread_W_M_imag_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sext_ln30_fu_292_p1 );

    SC_METHOD(thread_W_M_imag_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_W_M_real_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sext_ln30_fu_292_p1 );

    SC_METHOD(thread_W_M_real_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_add_ln33_fu_235_p2);
    sensitive << ( trunc_ln33_fu_231_p1 );

    SC_METHOD(thread_add_ln35_fu_249_p2);
    sensitive << ( trunc_ln35_fu_245_p1 );

    SC_METHOD(thread_add_ln703_1_fu_408_p2);
    sensitive << ( data_IN_M_imag_V_q0 );
    sensitive << ( p_Val2_5_fu_379_p4 );

    SC_METHOD(thread_add_ln703_fu_402_p2);
    sensitive << ( data_IN_M_real_V_q0 );
    sensitive << ( p_r_V_fu_370_p4 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln26_fu_259_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln26_fu_259_p2 );

    SC_METHOD(thread_butterfly_pass_1_fu_326_p3);
    sensitive << ( icmp_ln35_fu_315_p2 );
    sensitive << ( butterfly_pass_fu_320_p2 );

    SC_METHOD(thread_butterfly_pass_2_fu_342_p3);
    sensitive << ( butterfly_pass_0_reg_197 );
    sensitive << ( icmp_ln33_fu_304_p2 );
    sensitive << ( butterfly_pass_1_fu_326_p3 );

    SC_METHOD(thread_butterfly_pass_fu_320_p2);
    sensitive << ( butterfly_pass_0_reg_197 );

    SC_METHOD(thread_butterfly_span_fu_309_p2);
    sensitive << ( butterfly_span_0_reg_186 );

    SC_METHOD(thread_data_IN_M_imag_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sext_ln30_1_fu_298_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln31_fu_362_p1 );

    SC_METHOD(thread_data_IN_M_imag_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_data_IN_M_real_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sext_ln30_1_fu_298_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln31_fu_362_p1 );

    SC_METHOD(thread_data_IN_M_real_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_data_OUT_M_imag_V_address0);
    sensitive << ( sext_ln30_1_reg_488 );
    sensitive << ( sext_ln31_reg_539 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_data_OUT_M_imag_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_data_OUT_M_imag_V_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( add_ln703_1_reg_560 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sub_ln703_1_fu_395_p2 );

    SC_METHOD(thread_data_OUT_M_imag_V_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_data_OUT_M_real_V_address0);
    sensitive << ( sext_ln30_1_reg_488 );
    sensitive << ( sext_ln31_reg_539 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_data_OUT_M_real_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_data_OUT_M_real_V_d0);
    sensitive << ( add_ln703_reg_555 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sub_ln703_fu_388_p2 );

    SC_METHOD(thread_data_OUT_M_real_V_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_fu_426_p0);
    sensitive << ( sext_ln1118_2_reg_524 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_426_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sext_ln1118_3_fu_367_p1 );

    SC_METHOD(thread_grp_fu_433_p0);
    sensitive << ( sext_ln1118_reg_519 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_433_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sext_ln1118_3_fu_367_p1 );

    SC_METHOD(thread_i_fu_265_p2);
    sensitive << ( i_0_reg_208 );

    SC_METHOD(thread_icmp_ln26_fu_259_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_208 );

    SC_METHOD(thread_icmp_ln33_fu_304_p2);
    sensitive << ( zext_ln33_reg_455 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln26_fu_259_p2 );
    sensitive << ( butterfly_span_0_reg_186 );

    SC_METHOD(thread_icmp_ln35_fu_315_p2);
    sensitive << ( zext_ln35_reg_460 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln26_fu_259_p2 );
    sensitive << ( butterfly_pass_0_reg_197 );

    SC_METHOD(thread_index_fu_271_p2);
    sensitive << ( index_shift_cast_reg_445 );
    sensitive << ( butterfly_span_0_reg_186 );

    SC_METHOD(thread_index_shift_cast_fu_223_p1);
    sensitive << ( index_shift );

    SC_METHOD(thread_mul_ln1192_fu_420_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln1118_1_fu_354_p1 );

    SC_METHOD(thread_mul_ln700_fu_414_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln1118_1_fu_354_p1 );

    SC_METHOD(thread_p_Val2_5_fu_379_p4);
    sensitive << ( grp_fu_433_p3 );

    SC_METHOD(thread_p_r_V_fu_370_p4);
    sensitive << ( grp_fu_426_p3 );

    SC_METHOD(thread_pass_shift_cast_fu_219_p1);
    sensitive << ( pass_shift );

    SC_METHOD(thread_select_ln33_fu_334_p3);
    sensitive << ( icmp_ln33_fu_304_p2 );
    sensitive << ( butterfly_span_fu_309_p2 );

    SC_METHOD(thread_sext_ln1118_1_fu_354_p1);
    sensitive << ( data_IN_M_real_V_q0 );

    SC_METHOD(thread_sext_ln1118_2_fu_358_p1);
    sensitive << ( W_M_imag_V_q0 );

    SC_METHOD(thread_sext_ln1118_3_fu_367_p1);
    sensitive << ( data_IN_M_imag_V_lo_reg_514 );

    SC_METHOD(thread_sext_ln1118_fu_350_p1);
    sensitive << ( W_M_real_V_q0 );

    SC_METHOD(thread_sext_ln30_1_fu_298_p1);
    sensitive << ( Llimit_fu_287_p2 );

    SC_METHOD(thread_sext_ln30_fu_292_p1);
    sensitive << ( index_fu_271_p2 );

    SC_METHOD(thread_sext_ln31_fu_362_p1);
    sensitive << ( Ulimit_reg_473 );

    SC_METHOD(thread_shl_ln28_fu_276_p2);
    sensitive << ( pass_shift_cast_reg_440 );
    sensitive << ( butterfly_pass_0_reg_197 );

    SC_METHOD(thread_sub_ln703_1_fu_395_p2);
    sensitive << ( data_IN_M_imag_V_q0 );
    sensitive << ( p_Val2_5_fu_379_p4 );

    SC_METHOD(thread_sub_ln703_fu_388_p2);
    sensitive << ( data_IN_M_real_V_q0 );
    sensitive << ( p_r_V_fu_370_p4 );

    SC_METHOD(thread_trunc_ln33_fu_231_p1);
    sensitive << ( FFT_stage );

    SC_METHOD(thread_trunc_ln35_fu_245_p1);
    sensitive << ( pass_check );

    SC_METHOD(thread_zext_ln33_fu_241_p1);
    sensitive << ( add_ln33_fu_235_p2 );

    SC_METHOD(thread_zext_ln35_fu_255_p1);
    sensitive << ( add_ln35_fu_249_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln26_fu_259_p2 );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "FFT0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, FFT_stage, "(port)FFT_stage");
    sc_trace(mVcdFile, pass_check, "(port)pass_check");
    sc_trace(mVcdFile, index_shift, "(port)index_shift");
    sc_trace(mVcdFile, pass_shift, "(port)pass_shift");
    sc_trace(mVcdFile, data_IN_M_real_V_address0, "(port)data_IN_M_real_V_address0");
    sc_trace(mVcdFile, data_IN_M_real_V_ce0, "(port)data_IN_M_real_V_ce0");
    sc_trace(mVcdFile, data_IN_M_real_V_q0, "(port)data_IN_M_real_V_q0");
    sc_trace(mVcdFile, data_IN_M_imag_V_address0, "(port)data_IN_M_imag_V_address0");
    sc_trace(mVcdFile, data_IN_M_imag_V_ce0, "(port)data_IN_M_imag_V_ce0");
    sc_trace(mVcdFile, data_IN_M_imag_V_q0, "(port)data_IN_M_imag_V_q0");
    sc_trace(mVcdFile, data_OUT_M_real_V_address0, "(port)data_OUT_M_real_V_address0");
    sc_trace(mVcdFile, data_OUT_M_real_V_ce0, "(port)data_OUT_M_real_V_ce0");
    sc_trace(mVcdFile, data_OUT_M_real_V_we0, "(port)data_OUT_M_real_V_we0");
    sc_trace(mVcdFile, data_OUT_M_real_V_d0, "(port)data_OUT_M_real_V_d0");
    sc_trace(mVcdFile, data_OUT_M_imag_V_address0, "(port)data_OUT_M_imag_V_address0");
    sc_trace(mVcdFile, data_OUT_M_imag_V_ce0, "(port)data_OUT_M_imag_V_ce0");
    sc_trace(mVcdFile, data_OUT_M_imag_V_we0, "(port)data_OUT_M_imag_V_we0");
    sc_trace(mVcdFile, data_OUT_M_imag_V_d0, "(port)data_OUT_M_imag_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, W_M_real_V_address0, "W_M_real_V_address0");
    sc_trace(mVcdFile, W_M_real_V_ce0, "W_M_real_V_ce0");
    sc_trace(mVcdFile, W_M_real_V_q0, "W_M_real_V_q0");
    sc_trace(mVcdFile, W_M_imag_V_address0, "W_M_imag_V_address0");
    sc_trace(mVcdFile, W_M_imag_V_ce0, "W_M_imag_V_ce0");
    sc_trace(mVcdFile, W_M_imag_V_q0, "W_M_imag_V_q0");
    sc_trace(mVcdFile, pass_shift_cast_fu_219_p1, "pass_shift_cast_fu_219_p1");
    sc_trace(mVcdFile, pass_shift_cast_reg_440, "pass_shift_cast_reg_440");
    sc_trace(mVcdFile, index_shift_cast_fu_223_p1, "index_shift_cast_fu_223_p1");
    sc_trace(mVcdFile, index_shift_cast_reg_445, "index_shift_cast_reg_445");
    sc_trace(mVcdFile, FFT_stage_cast1_fu_227_p1, "FFT_stage_cast1_fu_227_p1");
    sc_trace(mVcdFile, FFT_stage_cast1_reg_450, "FFT_stage_cast1_reg_450");
    sc_trace(mVcdFile, zext_ln33_fu_241_p1, "zext_ln33_fu_241_p1");
    sc_trace(mVcdFile, zext_ln33_reg_455, "zext_ln33_reg_455");
    sc_trace(mVcdFile, zext_ln35_fu_255_p1, "zext_ln35_fu_255_p1");
    sc_trace(mVcdFile, zext_ln35_reg_460, "zext_ln35_reg_460");
    sc_trace(mVcdFile, i_fu_265_p2, "i_fu_265_p2");
    sc_trace(mVcdFile, i_reg_468, "i_reg_468");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, Ulimit_fu_281_p2, "Ulimit_fu_281_p2");
    sc_trace(mVcdFile, Ulimit_reg_473, "Ulimit_reg_473");
    sc_trace(mVcdFile, icmp_ln26_fu_259_p2, "icmp_ln26_fu_259_p2");
    sc_trace(mVcdFile, sext_ln30_1_fu_298_p1, "sext_ln30_1_fu_298_p1");
    sc_trace(mVcdFile, sext_ln30_1_reg_488, "sext_ln30_1_reg_488");
    sc_trace(mVcdFile, select_ln33_fu_334_p3, "select_ln33_fu_334_p3");
    sc_trace(mVcdFile, select_ln33_reg_504, "select_ln33_reg_504");
    sc_trace(mVcdFile, butterfly_pass_2_fu_342_p3, "butterfly_pass_2_fu_342_p3");
    sc_trace(mVcdFile, butterfly_pass_2_reg_509, "butterfly_pass_2_reg_509");
    sc_trace(mVcdFile, data_IN_M_imag_V_lo_reg_514, "data_IN_M_imag_V_lo_reg_514");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, sext_ln1118_fu_350_p1, "sext_ln1118_fu_350_p1");
    sc_trace(mVcdFile, sext_ln1118_reg_519, "sext_ln1118_reg_519");
    sc_trace(mVcdFile, sext_ln1118_2_fu_358_p1, "sext_ln1118_2_fu_358_p1");
    sc_trace(mVcdFile, sext_ln1118_2_reg_524, "sext_ln1118_2_reg_524");
    sc_trace(mVcdFile, mul_ln700_fu_414_p2, "mul_ln700_fu_414_p2");
    sc_trace(mVcdFile, mul_ln700_reg_529, "mul_ln700_reg_529");
    sc_trace(mVcdFile, mul_ln1192_fu_420_p2, "mul_ln1192_fu_420_p2");
    sc_trace(mVcdFile, mul_ln1192_reg_534, "mul_ln1192_reg_534");
    sc_trace(mVcdFile, sext_ln31_fu_362_p1, "sext_ln31_fu_362_p1");
    sc_trace(mVcdFile, sext_ln31_reg_539, "sext_ln31_reg_539");
    sc_trace(mVcdFile, add_ln703_fu_402_p2, "add_ln703_fu_402_p2");
    sc_trace(mVcdFile, add_ln703_reg_555, "add_ln703_reg_555");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, add_ln703_1_fu_408_p2, "add_ln703_1_fu_408_p2");
    sc_trace(mVcdFile, add_ln703_1_reg_560, "add_ln703_1_reg_560");
    sc_trace(mVcdFile, butterfly_span_0_reg_186, "butterfly_span_0_reg_186");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, butterfly_pass_0_reg_197, "butterfly_pass_0_reg_197");
    sc_trace(mVcdFile, i_0_reg_208, "i_0_reg_208");
    sc_trace(mVcdFile, sext_ln30_fu_292_p1, "sext_ln30_fu_292_p1");
    sc_trace(mVcdFile, sub_ln703_fu_388_p2, "sub_ln703_fu_388_p2");
    sc_trace(mVcdFile, sub_ln703_1_fu_395_p2, "sub_ln703_1_fu_395_p2");
    sc_trace(mVcdFile, trunc_ln33_fu_231_p1, "trunc_ln33_fu_231_p1");
    sc_trace(mVcdFile, add_ln33_fu_235_p2, "add_ln33_fu_235_p2");
    sc_trace(mVcdFile, trunc_ln35_fu_245_p1, "trunc_ln35_fu_245_p1");
    sc_trace(mVcdFile, add_ln35_fu_249_p2, "add_ln35_fu_249_p2");
    sc_trace(mVcdFile, shl_ln28_fu_276_p2, "shl_ln28_fu_276_p2");
    sc_trace(mVcdFile, index_fu_271_p2, "index_fu_271_p2");
    sc_trace(mVcdFile, Llimit_fu_287_p2, "Llimit_fu_287_p2");
    sc_trace(mVcdFile, icmp_ln35_fu_315_p2, "icmp_ln35_fu_315_p2");
    sc_trace(mVcdFile, butterfly_pass_fu_320_p2, "butterfly_pass_fu_320_p2");
    sc_trace(mVcdFile, icmp_ln33_fu_304_p2, "icmp_ln33_fu_304_p2");
    sc_trace(mVcdFile, butterfly_span_fu_309_p2, "butterfly_span_fu_309_p2");
    sc_trace(mVcdFile, butterfly_pass_1_fu_326_p3, "butterfly_pass_1_fu_326_p3");
    sc_trace(mVcdFile, grp_fu_426_p3, "grp_fu_426_p3");
    sc_trace(mVcdFile, grp_fu_433_p3, "grp_fu_433_p3");
    sc_trace(mVcdFile, p_r_V_fu_370_p4, "p_r_V_fu_370_p4");
    sc_trace(mVcdFile, p_Val2_5_fu_379_p4, "p_Val2_5_fu_379_p4");
    sc_trace(mVcdFile, mul_ln700_fu_414_p1, "mul_ln700_fu_414_p1");
    sc_trace(mVcdFile, sext_ln1118_1_fu_354_p1, "sext_ln1118_1_fu_354_p1");
    sc_trace(mVcdFile, mul_ln1192_fu_420_p0, "mul_ln1192_fu_420_p0");
    sc_trace(mVcdFile, grp_fu_426_p0, "grp_fu_426_p0");
    sc_trace(mVcdFile, grp_fu_426_p1, "grp_fu_426_p1");
    sc_trace(mVcdFile, sext_ln1118_3_fu_367_p1, "sext_ln1118_3_fu_367_p1");
    sc_trace(mVcdFile, grp_fu_433_p0, "grp_fu_433_p0");
    sc_trace(mVcdFile, grp_fu_433_p1, "grp_fu_433_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

FFT0::~FFT0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete W_M_real_V_U;
    delete W_M_imag_V_U;
    delete FFT_mul_mul_10s_1bkb_U1;
    delete FFT_mul_mul_16s_9cud_U2;
    delete FFT_mac_mulsub_9sdEe_U3;
    delete FFT_mac_muladd_10eOg_U4;
}

void FFT0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        butterfly_pass_0_reg_197 = butterfly_pass_2_reg_509.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        butterfly_pass_0_reg_197 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        butterfly_span_0_reg_186 = select_ln33_reg_504.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        butterfly_span_0_reg_186 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_0_reg_208 = i_reg_468.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_208 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        FFT_stage_cast1_reg_450 = FFT_stage_cast1_fu_227_p1.read();
        index_shift_cast_reg_445 = index_shift_cast_fu_223_p1.read();
        pass_shift_cast_reg_440 = pass_shift_cast_fu_219_p1.read();
        zext_ln33_reg_455 = zext_ln33_fu_241_p1.read();
        zext_ln35_reg_460 = zext_ln35_fu_255_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln26_fu_259_p2.read(), ap_const_lv1_0))) {
        Ulimit_reg_473 = Ulimit_fu_281_p2.read();
        butterfly_pass_2_reg_509 = butterfly_pass_2_fu_342_p3.read();
        select_ln33_reg_504 = select_ln33_fu_334_p3.read();
        sext_ln30_1_reg_488 = sext_ln30_1_fu_298_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        add_ln703_1_reg_560 = add_ln703_1_fu_408_p2.read();
        add_ln703_reg_555 = add_ln703_fu_402_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        data_IN_M_imag_V_lo_reg_514 = data_IN_M_imag_V_q0.read();
        mul_ln1192_reg_534 = mul_ln1192_fu_420_p2.read();
        mul_ln700_reg_529 = mul_ln700_fu_414_p2.read();
        sext_ln1118_2_reg_524 = sext_ln1118_2_fu_358_p1.read();
        sext_ln1118_reg_519 = sext_ln1118_fu_350_p1.read();
        sext_ln31_reg_539 = sext_ln31_fu_362_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_468 = i_fu_265_p2.read();
    }
}

void FFT0::thread_FFT_stage_cast1_fu_227_p1() {
    FFT_stage_cast1_fu_227_p1 = esl_zext<32,6>(FFT_stage.read());
}

void FFT0::thread_Llimit_fu_287_p2() {
    Llimit_fu_287_p2 = (!Ulimit_fu_281_p2.read().is_01() || !FFT_stage_cast1_reg_450.read().is_01())? sc_lv<32>(): (sc_bigint<32>(Ulimit_fu_281_p2.read()) + sc_biguint<32>(FFT_stage_cast1_reg_450.read()));
}

void FFT0::thread_Ulimit_fu_281_p2() {
    Ulimit_fu_281_p2 = (!butterfly_span_0_reg_186.read().is_01() || !shl_ln28_fu_276_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(butterfly_span_0_reg_186.read()) + sc_biguint<32>(shl_ln28_fu_276_p2.read()));
}

void FFT0::thread_W_M_imag_V_address0() {
    W_M_imag_V_address0 =  (sc_lv<4>) (sext_ln30_fu_292_p1.read());
}

void FFT0::thread_W_M_imag_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        W_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        W_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_W_M_real_V_address0() {
    W_M_real_V_address0 =  (sc_lv<4>) (sext_ln30_fu_292_p1.read());
}

void FFT0::thread_W_M_real_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        W_M_real_V_ce0 = ap_const_logic_1;
    } else {
        W_M_real_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_add_ln33_fu_235_p2() {
    add_ln33_fu_235_p2 = (!ap_const_lv5_1F.is_01() || !trunc_ln33_fu_231_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1F) + sc_biguint<5>(trunc_ln33_fu_231_p1.read()));
}

void FFT0::thread_add_ln35_fu_249_p2() {
    add_ln35_fu_249_p2 = (!ap_const_lv5_1F.is_01() || !trunc_ln35_fu_245_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1F) + sc_biguint<5>(trunc_ln35_fu_245_p1.read()));
}

void FFT0::thread_add_ln703_1_fu_408_p2() {
    add_ln703_1_fu_408_p2 = (!data_IN_M_imag_V_q0.read().is_01() || !p_Val2_5_fu_379_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(data_IN_M_imag_V_q0.read()) + sc_biguint<16>(p_Val2_5_fu_379_p4.read()));
}

void FFT0::thread_add_ln703_fu_402_p2() {
    add_ln703_fu_402_p2 = (!data_IN_M_real_V_q0.read().is_01() || !p_r_V_fu_370_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(data_IN_M_real_V_q0.read()) + sc_biguint<16>(p_r_V_fu_370_p4.read()));
}

void FFT0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void FFT0::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void FFT0::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void FFT0::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void FFT0::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void FFT0::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln26_fu_259_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void FFT0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void FFT0::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln26_fu_259_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void FFT0::thread_butterfly_pass_1_fu_326_p3() {
    butterfly_pass_1_fu_326_p3 = (!icmp_ln35_fu_315_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln35_fu_315_p2.read()[0].to_bool())? butterfly_pass_fu_320_p2.read(): ap_const_lv32_0);
}

void FFT0::thread_butterfly_pass_2_fu_342_p3() {
    butterfly_pass_2_fu_342_p3 = (!icmp_ln33_fu_304_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln33_fu_304_p2.read()[0].to_bool())? butterfly_pass_0_reg_197.read(): butterfly_pass_1_fu_326_p3.read());
}

void FFT0::thread_butterfly_pass_fu_320_p2() {
    butterfly_pass_fu_320_p2 = (!butterfly_pass_0_reg_197.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(butterfly_pass_0_reg_197.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void FFT0::thread_butterfly_span_fu_309_p2() {
    butterfly_span_fu_309_p2 = (!butterfly_span_0_reg_186.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(butterfly_span_0_reg_186.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void FFT0::thread_data_IN_M_imag_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        data_IN_M_imag_V_address0 =  (sc_lv<5>) (sext_ln31_fu_362_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_IN_M_imag_V_address0 =  (sc_lv<5>) (sext_ln30_1_fu_298_p1.read());
    } else {
        data_IN_M_imag_V_address0 = "XXXXX";
    }
}

void FFT0::thread_data_IN_M_imag_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        data_IN_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        data_IN_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_IN_M_real_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        data_IN_M_real_V_address0 =  (sc_lv<5>) (sext_ln31_fu_362_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_IN_M_real_V_address0 =  (sc_lv<5>) (sext_ln30_1_fu_298_p1.read());
    } else {
        data_IN_M_real_V_address0 = "XXXXX";
    }
}

void FFT0::thread_data_IN_M_real_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        data_IN_M_real_V_ce0 = ap_const_logic_1;
    } else {
        data_IN_M_real_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_OUT_M_imag_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_OUT_M_imag_V_address0 =  (sc_lv<5>) (sext_ln31_reg_539.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        data_OUT_M_imag_V_address0 =  (sc_lv<5>) (sext_ln30_1_reg_488.read());
    } else {
        data_OUT_M_imag_V_address0 = "XXXXX";
    }
}

void FFT0::thread_data_OUT_M_imag_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        data_OUT_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        data_OUT_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_OUT_M_imag_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_OUT_M_imag_V_d0 = add_ln703_1_reg_560.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        data_OUT_M_imag_V_d0 = sub_ln703_1_fu_395_p2.read();
    } else {
        data_OUT_M_imag_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void FFT0::thread_data_OUT_M_imag_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        data_OUT_M_imag_V_we0 = ap_const_logic_1;
    } else {
        data_OUT_M_imag_V_we0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_OUT_M_real_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_OUT_M_real_V_address0 =  (sc_lv<5>) (sext_ln31_reg_539.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        data_OUT_M_real_V_address0 =  (sc_lv<5>) (sext_ln30_1_reg_488.read());
    } else {
        data_OUT_M_real_V_address0 = "XXXXX";
    }
}

void FFT0::thread_data_OUT_M_real_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        data_OUT_M_real_V_ce0 = ap_const_logic_1;
    } else {
        data_OUT_M_real_V_ce0 = ap_const_logic_0;
    }
}

void FFT0::thread_data_OUT_M_real_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        data_OUT_M_real_V_d0 = add_ln703_reg_555.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        data_OUT_M_real_V_d0 = sub_ln703_fu_388_p2.read();
    } else {
        data_OUT_M_real_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void FFT0::thread_data_OUT_M_real_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        data_OUT_M_real_V_we0 = ap_const_logic_1;
    } else {
        data_OUT_M_real_V_we0 = ap_const_logic_0;
    }
}

void FFT0::thread_grp_fu_426_p0() {
    grp_fu_426_p0 =  (sc_lv<9>) (sext_ln1118_2_reg_524.read());
}

void FFT0::thread_grp_fu_426_p1() {
    grp_fu_426_p1 =  (sc_lv<16>) (sext_ln1118_3_fu_367_p1.read());
}

void FFT0::thread_grp_fu_433_p0() {
    grp_fu_433_p0 =  (sc_lv<10>) (sext_ln1118_reg_519.read());
}

void FFT0::thread_grp_fu_433_p1() {
    grp_fu_433_p1 =  (sc_lv<16>) (sext_ln1118_3_fu_367_p1.read());
}

void FFT0::thread_i_fu_265_p2() {
    i_fu_265_p2 = (!i_0_reg_208.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_reg_208.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void FFT0::thread_icmp_ln26_fu_259_p2() {
    icmp_ln26_fu_259_p2 = (!i_0_reg_208.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_208.read() == ap_const_lv5_10);
}

void FFT0::thread_icmp_ln33_fu_304_p2() {
    icmp_ln33_fu_304_p2 = (!butterfly_span_0_reg_186.read().is_01() || !zext_ln33_reg_455.read().is_01())? sc_lv<1>(): (sc_bigint<32>(butterfly_span_0_reg_186.read()) < sc_bigint<32>(zext_ln33_reg_455.read()));
}

void FFT0::thread_icmp_ln35_fu_315_p2() {
    icmp_ln35_fu_315_p2 = (!butterfly_pass_0_reg_197.read().is_01() || !zext_ln35_reg_460.read().is_01())? sc_lv<1>(): (sc_bigint<32>(butterfly_pass_0_reg_197.read()) < sc_bigint<32>(zext_ln35_reg_460.read()));
}

void FFT0::thread_index_fu_271_p2() {
    index_fu_271_p2 = (!index_shift_cast_reg_445.read().is_01())? sc_lv<32>(): butterfly_span_0_reg_186.read() << (unsigned short)index_shift_cast_reg_445.read().to_uint();
}

void FFT0::thread_index_shift_cast_fu_223_p1() {
    index_shift_cast_fu_223_p1 = esl_zext<32,4>(index_shift.read());
}

void FFT0::thread_mul_ln1192_fu_420_p0() {
    mul_ln1192_fu_420_p0 =  (sc_lv<16>) (sext_ln1118_1_fu_354_p1.read());
}

void FFT0::thread_mul_ln700_fu_414_p1() {
    mul_ln700_fu_414_p1 =  (sc_lv<16>) (sext_ln1118_1_fu_354_p1.read());
}

void FFT0::thread_p_Val2_5_fu_379_p4() {
    p_Val2_5_fu_379_p4 = grp_fu_433_p3.read().range(23, 8);
}

void FFT0::thread_p_r_V_fu_370_p4() {
    p_r_V_fu_370_p4 = grp_fu_426_p3.read().range(23, 8);
}

void FFT0::thread_pass_shift_cast_fu_219_p1() {
    pass_shift_cast_fu_219_p1 = esl_zext<32,4>(pass_shift.read());
}

void FFT0::thread_select_ln33_fu_334_p3() {
    select_ln33_fu_334_p3 = (!icmp_ln33_fu_304_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln33_fu_304_p2.read()[0].to_bool())? butterfly_span_fu_309_p2.read(): ap_const_lv32_0);
}

void FFT0::thread_sext_ln1118_1_fu_354_p1() {
    sext_ln1118_1_fu_354_p1 = esl_sext<24,16>(data_IN_M_real_V_q0.read());
}

void FFT0::thread_sext_ln1118_2_fu_358_p1() {
    sext_ln1118_2_fu_358_p1 = esl_sext<24,9>(W_M_imag_V_q0.read());
}

void FFT0::thread_sext_ln1118_3_fu_367_p1() {
    sext_ln1118_3_fu_367_p1 = esl_sext<24,16>(data_IN_M_imag_V_lo_reg_514.read());
}

void FFT0::thread_sext_ln1118_fu_350_p1() {
    sext_ln1118_fu_350_p1 = esl_sext<24,10>(W_M_real_V_q0.read());
}

void FFT0::thread_sext_ln30_1_fu_298_p1() {
    sext_ln30_1_fu_298_p1 = esl_sext<64,32>(Llimit_fu_287_p2.read());
}

void FFT0::thread_sext_ln30_fu_292_p1() {
    sext_ln30_fu_292_p1 = esl_sext<64,32>(index_fu_271_p2.read());
}

void FFT0::thread_sext_ln31_fu_362_p1() {
    sext_ln31_fu_362_p1 = esl_sext<64,32>(Ulimit_reg_473.read());
}

void FFT0::thread_shl_ln28_fu_276_p2() {
    shl_ln28_fu_276_p2 = (!pass_shift_cast_reg_440.read().is_01())? sc_lv<32>(): butterfly_pass_0_reg_197.read() << (unsigned short)pass_shift_cast_reg_440.read().to_uint();
}

void FFT0::thread_sub_ln703_1_fu_395_p2() {
    sub_ln703_1_fu_395_p2 = (!data_IN_M_imag_V_q0.read().is_01() || !p_Val2_5_fu_379_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(data_IN_M_imag_V_q0.read()) - sc_biguint<16>(p_Val2_5_fu_379_p4.read()));
}

void FFT0::thread_sub_ln703_fu_388_p2() {
    sub_ln703_fu_388_p2 = (!data_IN_M_real_V_q0.read().is_01() || !p_r_V_fu_370_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(data_IN_M_real_V_q0.read()) - sc_biguint<16>(p_r_V_fu_370_p4.read()));
}

void FFT0::thread_trunc_ln33_fu_231_p1() {
    trunc_ln33_fu_231_p1 = FFT_stage.read().range(5-1, 0);
}

void FFT0::thread_trunc_ln35_fu_245_p1() {
    trunc_ln35_fu_245_p1 = pass_check.read().range(5-1, 0);
}

void FFT0::thread_zext_ln33_fu_241_p1() {
    zext_ln33_fu_241_p1 = esl_zext<32,5>(add_ln33_fu_235_p2.read());
}

void FFT0::thread_zext_ln35_fu_255_p1() {
    zext_ln35_fu_255_p1 = esl_zext<32,5>(add_ln35_fu_249_p2.read());
}

void FFT0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln26_fu_259_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

}

